blank_issues_enabled: false
contact_links:
  - name: Question or Discussion
    url: https://github.com/c4a8-azure/marinatemd/discussions
    about: Ask questions or discuss ideas with the community
  - name: Documentation
    url: https://github.com/c4a8-azure/marinatemd/blob/main/README.md
    about: Read the project documentation
