variable: app_config
version: "1"
schema:
    cache:
        _meta:
            description: '# TODO: Add description for cache'
        children:
            redis_url:
                type: string
                required: true
                description: '# TODO: Add description for redis_url'
            ttl:
                type: number
                description: '# TODO: Add description for ttl'
        type: object
    database:
        _meta:
            description: '# TODO: Add description for database'
        children:
            host:
                type: string
                required: true
                description: '# TODO: Add description for host'
            port:
                type: number
                description: '# TODO: Add description for port'
            ssl_mode:
                type: string
                description: '# TODO: Add description for ssl_mode'
        type: object
