variable: configure_adds_resources
version: "1"
schema:
    advanced:
        _marinate:
            description: '# TODO: Add description for advanced'
        type: any
    location:
        _marinate:
            description: '# TODO: Add description for location'
        type: string
    settings:
        _marinate:
            description: '# TODO: Add description for settings'
        type: object
        forests:
            _marinate:
                description: '# TODO: Add description for forests'
            type: list
            element_type: object
            config:
                _marinate:
                    description: '# TODO: Add description for config'
                type: object
                backup_policy:
                    _marinate:
                        description: '# TODO: Add description for backup_policy'
                    type: object
                    enhanced:
                        _marinate:
                            description: '# TODO: Add description for enhanced'
                        type: bool
                network:
                    _marinate:
                        description: '# TODO: Add description for network'
                    type: object
                network_security_rules:
                    _marinate:
                        description: '# TODO: Add description for network_security_rules'
                    type: object
                    custom_prefixes:
                        _marinate:
                            description: '# TODO: Add description for custom_prefixes'
                        type: any
                    remote_address_prefixes:
                        _marinate:
                            description: '# TODO: Add description for remote_address_prefixes'
                        type: list
                        element_type: string
                recovery_service:
                    _marinate:
                        description: '# TODO: Add description for recovery_service'
                    type: object
                    immutability:
                        _marinate:
                            description: '# TODO: Add description for immutability'
                        type: string
            domains:
                _marinate:
                    description: '# TODO: Add description for domains'
                type: list
                element_type: object
                config:
                    _marinate:
                        description: '# TODO: Add description for config'
                    type: object
                    domain_controllers:
                        _marinate:
                            description: '# TODO: Add description for domain_controllers'
                        type: list
                        element_type: object
                        azure_update:
                            _marinate:
                                description: '# TODO: Add description for azure_update'
                            type: object
                            enabled:
                                _marinate:
                                    description: '# TODO: Add description for enabled'
                                type: bool
                            template:
                                _marinate:
                                    description: '# TODO: Add description for template'
                                type: string
                        computer_name:
                            _marinate:
                                description: '# TODO: Add description for computer_name'
                            type: string
                        data_disk_size:
                            _marinate:
                                description: '# TODO: Add description for data_disk_size'
                            type: number
                        dns_servers:
                            _marinate:
                                description: '# TODO: Add description for dns_servers'
                            type: list
                            element_type: string
                        enable_boot_diagnostics:
                            _marinate:
                                description: '# TODO: Add description for enable_boot_diagnostics'
                            type: bool
                        enabled:
                            _marinate:
                                description: '# TODO: Add description for enabled'
                            type: bool
                        image_sku:
                            _marinate:
                                description: '# TODO: Add description for image_sku'
                            type: string
                        meta_data:
                            _marinate:
                                description: '# TODO: Add description for meta_data'
                            type: object
                            tags:
                                _marinate:
                                    description: '# TODO: Add description for tags'
                                type: map
                                value_type: string
                        name:
                            _marinate:
                                description: '# TODO: Add description for name'
                            type: string
                        role_assignments:
                            _marinate:
                                description: '# TODO: Add description for role_assignments'
                            type: list
                            element_type: object
                            principal_id:
                                _marinate:
                                    description: '# TODO: Add description for principal_id'
                                type: string
                                required: true
                            role_definition_name:
                                _marinate:
                                    description: '# TODO: Add description for role_definition_name'
                                type: string
                                required: true
                        size:
                            _marinate:
                                description: '# TODO: Add description for size'
                            type: string
                        use_enhanced_backup:
                            _marinate:
                                description: '# TODO: Add description for use_enhanced_backup'
                            type: bool
                        use_trusted_launch:
                            _marinate:
                                description: '# TODO: Add description for use_trusted_launch'
                            type: bool
                    domain_type:
                        _marinate:
                            description: '# TODO: Add description for domain_type'
                        type: string
                    network:
                        _marinate:
                            description: '# TODO: Add description for network'
                        type: object
                    network_security_rules:
                        _marinate:
                            description: '# TODO: Add description for network_security_rules'
                        type: object
                        custom_prefixes:
                            _marinate:
                                description: '# TODO: Add description for custom_prefixes'
                            type: any
                        remote_address_prefixes:
                            _marinate:
                                description: '# TODO: Add description for remote_address_prefixes'
                            type: list
                            element_type: string
                    optional_routes:
                        _marinate:
                            description: '# TODO: Add description for optional_routes'
                        type: list
                        element_type: string
                    parent_domain_name:
                        _marinate:
                            description: '# TODO: Add description for parent_domain_name'
                        type: string
                    users:
                        _marinate:
                            description: '# TODO: Add description for users'
                        type: object
                        customer_role_assignment:
                            _marinate:
                                description: '# TODO: Add description for customer_role_assignment'
                            type: list
                            element_type: string
                fqdn:
                    _marinate:
                        description: '# TODO: Add description for fqdn'
                    type: string
                index:
                    _marinate:
                        description: '# TODO: Add description for index'
                    type: number
                netbios_name:
                    _marinate:
                        description: '# TODO: Add description for netbios_name'
                    type: string
            enabled:
                _marinate:
                    description: '# TODO: Add description for enabled'
                type: bool
            fqdn:
                _marinate:
                    description: '# TODO: Add description for fqdn'
                type: string
            index:
                _marinate:
                    description: '# TODO: Add description for index'
                type: number
            netbios_name:
                _marinate:
                    description: '# TODO: Add description for netbios_name'
                type: string
            test:
                _marinate:
                    description: '# TODO: Add description for test'
                type: string
        maintenance_templates:
            _marinate:
                description: '# TODO: Add description for maintenance_templates'
            type: list
            element_type: object
            classifications_to_include:
                _marinate:
                    description: '# TODO: Add description for classifications_to_include'
                type: list
                element_type: string
            duration:
                _marinate:
                    description: '# TODO: Add description for duration'
                type: string
            expiration_date_time:
                _marinate:
                    description: '# TODO: Add description for expiration_date_time'
                type: string
            in_guest_user_patch_mode:
                _marinate:
                    description: '# TODO: Add description for in_guest_user_patch_mode'
                type: string
            name:
                _marinate:
                    description: '# TODO: Add description for name'
                type: string
                required: true
            reboot:
                _marinate:
                    description: '# TODO: Add description for reboot'
                type: string
            recur_every:
                _marinate:
                    description: '# TODO: Add description for recur_every'
                type: string
                required: true
            scope:
                _marinate:
                    description: '# TODO: Add description for scope'
                type: string
            start_date_time:
                _marinate:
                    description: '# TODO: Add description for start_date_time'
                type: string
                required: true
            time_zone:
                _marinate:
                    description: '# TODO: Add description for time_zone'
                type: string
            visibility:
                _marinate:
                    description: '# TODO: Add description for visibility'
                type: string
    tags:
        _marinate:
            description: '# TODO: Add description for tags'
        type: any
